[2025-02-13T19:43:45.110+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T19:43:45.143+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-13T19:43:43.310638+00:00 [queued]>
[2025-02-13T19:43:45.159+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-13T19:43:43.310638+00:00 [queued]>
[2025-02-13T19:43:45.161+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-13T19:43:45.184+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_spark_script> on 2025-02-13 19:43:43.310638+00:00
[2025-02-13T19:43:45.193+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1624) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T19:43:45.195+0000] {standard_task_runner.py:72} INFO - Started process 1625 to run task
[2025-02-13T19:43:45.196+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ing_mov_20_21', 'run_spark_script', 'manual__2025-02-13T19:43:43.310638+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/scriptteste.py', '--cfg-path', '/tmp/tmp1iisas57']
[2025-02-13T19:43:45.198+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask run_spark_script
[2025-02-13T19:43:45.275+0000] {task_command.py:467} INFO - Running <TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-13T19:43:43.310638+00:00 [running]> on host 61e67732f9c4
[2025-02-13T19:43:45.421+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ing_mov_20_21' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T19:43:43.310638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T19:43:43.310638+00:00'
[2025-02-13T19:43:45.423+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T19:43:45.446+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-13T19:43:45.448+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/bitnami/spark/scripts/ing_mov_20_21.py']
[2025-02-13T19:43:45.461+0000] {subprocess.py:99} INFO - Output:
[2025-02-13T19:43:51.470+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SparkContext: Running Spark version 3.5.4
[2025-02-13T19:43:51.475+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-02-13T19:43:51.476+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SparkContext: Java version 17.0.14
[2025-02-13T19:43:51.565+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-13T19:43:51.738+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO ResourceUtils: ==============================================================
[2025-02-13T19:43:51.739+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-02-13T19:43:51.740+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO ResourceUtils: ==============================================================
[2025-02-13T19:43:51.741+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SparkContext: Submitted application: Movies_20_21
[2025-02-13T19:43:51.796+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 2, script: , vendor: , memory -> name: memory, amount: 12288, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-02-13T19:43:51.816+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO ResourceProfile: Limiting resource is cpus at 2 tasks per executor
[2025-02-13T19:43:51.819+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-02-13T19:43:51.950+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SecurityManager: Changing view acls to: ***
[2025-02-13T19:43:51.951+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SecurityManager: Changing modify acls to: ***
[2025-02-13T19:43:51.953+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SecurityManager: Changing view acls groups to:
[2025-02-13T19:43:51.954+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SecurityManager: Changing modify acls groups to:
[2025-02-13T19:43:51.955+0000] {subprocess.py:106} INFO - 25/02/13 19:43:51 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-02-13T19:43:52.419+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO Utils: Successfully started service 'sparkDriver' on port 41781.
[2025-02-13T19:43:52.483+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO SparkEnv: Registering MapOutputTracker
[2025-02-13T19:43:52.572+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO SparkEnv: Registering BlockManagerMaster
[2025-02-13T19:43:52.612+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-02-13T19:43:52.615+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-02-13T19:43:52.625+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-02-13T19:43:52.678+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-845e87f5-8acc-49d8-97bd-b5e4853b641f
[2025-02-13T19:43:52.705+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-02-13T19:43:52.740+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-02-13T19:43:52.997+0000] {subprocess.py:106} INFO - 25/02/13 19:43:52 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-02-13T19:43:53.140+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-02-13T19:43:53.361+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-02-13T19:43:53.431+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO TransportClientFactory: Successfully created connection to spark/172.18.0.6:7077 after 38 ms (0 ms spent in bootstraps)
[2025-02-13T19:43:53.572+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250213194353-0003
[2025-02-13T19:43:53.591+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250213194353-0003/0 on worker-20250213174710-172.18.0.7-45575 (172.18.0.7:45575) with 2 core(s)
[2025-02-13T19:43:53.599+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneSchedulerBackend: Granted executor ID app-20250213194353-0003/0 on hostPort 172.18.0.7:45575 with 2 core(s), 12.0 GiB RAM
[2025-02-13T19:43:53.616+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 44387.
[2025-02-13T19:43:53.623+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO NettyBlockTransferService: Server created on 61e67732f9c4:44387
[2025-02-13T19:43:53.624+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250213194353-0003/1 on worker-20250213174710-172.18.0.4-38387 (172.18.0.4:38387) with 2 core(s)
[2025-02-13T19:43:53.629+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneSchedulerBackend: Granted executor ID app-20250213194353-0003/1 on hostPort 172.18.0.4:38387 with 2 core(s), 12.0 GiB RAM
[2025-02-13T19:43:53.632+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-02-13T19:43:53.634+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 61e67732f9c4, 44387, None)
[2025-02-13T19:43:53.635+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO BlockManagerMasterEndpoint: Registering block manager 61e67732f9c4:44387 with 434.4 MiB RAM, BlockManagerId(driver, 61e67732f9c4, 44387, None)
[2025-02-13T19:43:53.636+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 61e67732f9c4, 44387, None)
[2025-02-13T19:43:53.637+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 61e67732f9c4, 44387, None)
[2025-02-13T19:43:53.653+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250213194353-0003/1 is now RUNNING
[2025-02-13T19:43:53.655+0000] {subprocess.py:106} INFO - 25/02/13 19:43:53 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250213194353-0003/0 is now RUNNING
[2025-02-13T19:43:54.362+0000] {subprocess.py:106} INFO - 25/02/13 19:43:54 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-02-13T19:44:00.767+0000] {subprocess.py:106} INFO - 25/02/13 19:44:00 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.4:57156) with ID 1,  ResourceProfileId 0
[2025-02-13T19:44:01.038+0000] {subprocess.py:106} INFO - 25/02/13 19:44:01 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.7:40410) with ID 0,  ResourceProfileId 0
[2025-02-13T19:44:01.062+0000] {subprocess.py:106} INFO - 25/02/13 19:44:01 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.4:42033 with 7.0 GiB RAM, BlockManagerId(1, 172.18.0.4, 42033, None)
[2025-02-13T19:44:01.323+0000] {subprocess.py:106} INFO - 25/02/13 19:44:01 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.7:43393 with 7.0 GiB RAM, BlockManagerId(0, 172.18.0.7, 43393, None)
[2025-02-13T20:04:51.230+0000] {subprocess.py:106} INFO - 25/02/13 20:04:51 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-02-13T20:04:51.250+0000] {subprocess.py:106} INFO - 25/02/13 20:04:51 INFO SharedState: Warehouse path is 'file:/tmp/***tmpgvhxe31f/spark-warehouse'.
[2025-02-13T20:04:54.907+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-13T20:04:54.908+0000] {subprocess.py:106} INFO -   File "/opt/bitnami/spark/scripts/ing_mov_20_21.py", line 131, in <module>
[2025-02-13T20:04:54.911+0000] {subprocess.py:106} INFO -     .save("s3a://bronze/movie_20_21/")
[2025-02-13T20:04:54.912+0000] {subprocess.py:106} INFO -      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-13T20:04:54.912+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1463, in save
[2025-02-13T20:04:54.913+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-02-13T20:04:54.914+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-02-13T20:04:54.915+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-02-13T20:04:54.916+0000] {subprocess.py:106} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o57.save.
[2025-02-13T20:04:54.917+0000] {subprocess.py:106} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-13T20:04:54.917+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-02-13T20:04:54.920+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-02-13T20:04:54.921+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-02-13T20:04:54.922+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-02-13T20:04:54.923+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-02-13T20:04:54.924+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-02-13T20:04:54.924+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-02-13T20:04:54.925+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-02-13T20:04:54.926+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:454)
[2025-02-13T20:04:54.926+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:530)
[2025-02-13T20:04:54.927+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:391)
[2025-02-13T20:04:54.928+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:364)
[2025-02-13T20:04:54.928+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:243)
[2025-02-13T20:04:54.929+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-13T20:04:54.930+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-02-13T20:04:54.931+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-13T20:04:54.931+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-02-13T20:04:54.932+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-02-13T20:04:54.933+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-02-13T20:04:54.934+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-02-13T20:04:54.934+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-02-13T20:04:54.935+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-02-13T20:04:54.935+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-02-13T20:04:54.936+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-02-13T20:04:54.937+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-02-13T20:04:54.938+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-13T20:04:54.939+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-02-13T20:04:54.941+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-02-13T20:04:54.942+0000] {subprocess.py:106} INFO - 	... 24 more
[2025-02-13T20:04:54.943+0000] {subprocess.py:106} INFO - 
[2025-02-13T20:04:55.303+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO SparkContext: Invoking stop() from shutdown hook
[2025-02-13T20:04:55.304+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-02-13T20:04:55.323+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO SparkUI: Stopped Spark web UI at http://61e67732f9c4:4040
[2025-02-13T20:04:55.330+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-02-13T20:04:55.331+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-02-13T20:04:55.375+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-02-13T20:04:55.426+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO MemoryStore: MemoryStore cleared
[2025-02-13T20:04:55.428+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO BlockManager: BlockManager stopped
[2025-02-13T20:04:55.437+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-02-13T20:04:55.448+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-02-13T20:04:55.466+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO SparkContext: Successfully stopped SparkContext
[2025-02-13T20:04:55.467+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO ShutdownHookManager: Shutdown hook called
[2025-02-13T20:04:55.471+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-a767ad97-88d1-40de-9a65-f7e1663c74a4
[2025-02-13T20:04:55.478+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-22159f3b-1078-47d3-9708-1ac5b08a8fc2
[2025-02-13T20:04:55.484+0000] {subprocess.py:106} INFO - 25/02/13 20:04:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-a767ad97-88d1-40de-9a65-f7e1663c74a4/pyspark-6d8d606d-5ed5-46a9-96c0-f5b2292683e7
[2025-02-13T20:04:55.546+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-13T20:04:55.568+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-13T20:04:55.583+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=ing_mov_20_21, task_id=run_spark_script, run_id=manual__2025-02-13T19:43:43.310638+00:00, execution_date=20250213T194343, start_date=20250213T194345, end_date=20250213T200455
[2025-02-13T20:04:55.787+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T20:04:55.788+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task run_spark_script (Bash command failed. The command returned a non-zero exit code 1.; 1625)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-13T20:04:55.823+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-13T20:04:55.860+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T20:04:55.991+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
