[2025-02-21T12:38:13.028+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T12:38:13.047+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:00:42.315427+00:00 [queued]>
[2025-02-21T12:38:13.055+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:00:42.315427+00:00 [queued]>
[2025-02-21T12:38:13.056+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-21T12:38:13.069+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_spark_script> on 2025-02-21 12:00:42.315427+00:00
[2025-02-21T12:38:13.073+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=842) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T12:38:13.075+0000] {standard_task_runner.py:72} INFO - Started process 843 to run task
[2025-02-21T12:38:13.075+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ing_mov_20_21', 'run_spark_script', 'manual__2025-02-21T12:00:42.315427+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/scriptteste.py', '--cfg-path', '/tmp/tmpha35j4n3']
[2025-02-21T12:38:13.076+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask run_spark_script
[2025-02-21T12:38:13.125+0000] {task_command.py:467} INFO - Running <TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-21T12:00:42.315427+00:00 [running]> on host b2dbcea502fb
[2025-02-21T12:38:13.198+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ing_mov_20_21' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T12:00:42.315427+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T12:00:42.315427+00:00'
[2025-02-21T12:38:13.198+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T12:38:13.211+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-21T12:38:13.212+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit /opt/bitnami/spark/scripts/ing_mov_20_21.py']
[2025-02-21T12:38:13.219+0000] {subprocess.py:99} INFO - Output:
[2025-02-21T12:38:13.255+0000] {subprocess.py:106} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-21T12:38:16.005+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkContext: Running Spark version 3.5.0
[2025-02-21T12:38:16.006+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-02-21T12:38:16.007+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkContext: Java version 17.0.14
[2025-02-21T12:38:16.053+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-21T12:38:16.136+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO ResourceUtils: ==============================================================
[2025-02-21T12:38:16.137+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-02-21T12:38:16.139+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO ResourceUtils: ==============================================================
[2025-02-21T12:38:16.140+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkContext: Submitted application: Movies_20_21
[2025-02-21T12:38:16.172+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 8192, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-02-21T12:38:16.181+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-02-21T12:38:16.183+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-02-21T12:38:16.229+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SecurityManager: Changing view acls to: ***
[2025-02-21T12:38:16.230+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SecurityManager: Changing modify acls to: ***
[2025-02-21T12:38:16.231+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SecurityManager: Changing view acls groups to:
[2025-02-21T12:38:16.231+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SecurityManager: Changing modify acls groups to:
[2025-02-21T12:38:16.232+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-02-21T12:38:16.427+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO Utils: Successfully started service 'sparkDriver' on port 33429.
[2025-02-21T12:38:16.458+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkEnv: Registering MapOutputTracker
[2025-02-21T12:38:16.488+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkEnv: Registering BlockManagerMaster
[2025-02-21T12:38:16.502+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-02-21T12:38:16.502+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-02-21T12:38:16.505+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-02-21T12:38:16.520+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-6ba55d8a-0719-4666-92d0-f18e77f7a91d
[2025-02-21T12:38:16.531+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-02-21T12:38:16.552+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-02-21T12:38:16.672+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-02-21T12:38:16.711+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-02-21T12:38:16.717+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-02-21T12:38:16.833+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-02-21T12:38:16.867+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO TransportClientFactory: Successfully created connection to spark/172.18.0.7:7077 after 19 ms (0 ms spent in bootstraps)
[2025-02-21T12:38:16.939+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250221123816-0002
[2025-02-21T12:38:16.945+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40627.
[2025-02-21T12:38:16.946+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO NettyBlockTransferService: Server created on b2dbcea502fb:40627
[2025-02-21T12:38:16.947+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-02-21T12:38:16.951+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, b2dbcea502fb, 40627, None)
[2025-02-21T12:38:16.954+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO BlockManagerMasterEndpoint: Registering block manager b2dbcea502fb:40627 with 434.4 MiB RAM, BlockManagerId(driver, b2dbcea502fb, 40627, None)
[2025-02-21T12:38:16.955+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, b2dbcea502fb, 40627, None)
[2025-02-21T12:38:16.956+0000] {subprocess.py:106} INFO - 25/02/21 12:38:16 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, b2dbcea502fb, 40627, None)
[2025-02-21T12:38:17.084+0000] {subprocess.py:106} INFO - 25/02/21 12:38:17 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-02-21T13:08:06.924+0000] {subprocess.py:106} INFO - 25/02/21 13:08:06 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-02-21T13:08:06.931+0000] {subprocess.py:106} INFO - 25/02/21 13:08:06 INFO SharedState: Warehouse path is 'file:/tmp/***tmprjxwml9w/spark-warehouse'.
[2025-02-21T13:08:08.321+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-21T13:08:08.321+0000] {subprocess.py:106} INFO -   File "/opt/bitnami/spark/scripts/ing_mov_20_21.py", line 131, in <module>
[2025-02-21T13:08:08.322+0000] {subprocess.py:106} INFO -     .save("s3a://bronze/movie_20_21/")
[2025-02-21T13:08:08.323+0000] {subprocess.py:106} INFO -      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-21T13:08:08.324+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 1463, in save
[2025-02-21T13:08:08.324+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-02-21T13:08:08.325+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-02-21T13:08:08.325+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-02-21T13:08:08.330+0000] {subprocess.py:106} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o57.save.
[2025-02-21T13:08:08.331+0000] {subprocess.py:106} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-21T13:08:08.331+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-02-21T13:08:08.331+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-02-21T13:08:08.332+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-02-21T13:08:08.332+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-02-21T13:08:08.332+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-02-21T13:08:08.334+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-02-21T13:08:08.334+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-02-21T13:08:08.335+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-02-21T13:08:08.335+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWritingFileFormat(DataSource.scala:454)
[2025-02-21T13:08:08.335+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.planForWriting(DataSource.scala:530)
[2025-02-21T13:08:08.336+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
[2025-02-21T13:08:08.339+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
[2025-02-21T13:08:08.341+0000] {subprocess.py:106} INFO - 	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:240)
[2025-02-21T13:08:08.341+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-21T13:08:08.342+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-02-21T13:08:08.342+0000] {subprocess.py:106} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-21T13:08:08.343+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-02-21T13:08:08.356+0000] {subprocess.py:106} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-02-21T13:08:08.356+0000] {subprocess.py:106} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-02-21T13:08:08.357+0000] {subprocess.py:106} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-02-21T13:08:08.357+0000] {subprocess.py:106} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-02-21T13:08:08.358+0000] {subprocess.py:106} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-02-21T13:08:08.358+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-02-21T13:08:08.358+0000] {subprocess.py:106} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-02-21T13:08:08.359+0000] {subprocess.py:106} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-02-21T13:08:08.359+0000] {subprocess.py:106} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-02-21T13:08:08.360+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-02-21T13:08:08.360+0000] {subprocess.py:106} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-02-21T13:08:08.360+0000] {subprocess.py:106} INFO - 	... 24 more
[2025-02-21T13:08:08.361+0000] {subprocess.py:106} INFO - 
[2025-02-21T13:08:08.523+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkContext: Invoking stop() from shutdown hook
[2025-02-21T13:08:08.524+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-02-21T13:08:08.530+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkUI: Stopped Spark web UI at http://b2dbcea502fb:4041
[2025-02-21T13:08:08.535+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-02-21T13:08:08.537+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-02-21T13:08:08.563+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-02-21T13:08:08.600+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO MemoryStore: MemoryStore cleared
[2025-02-21T13:08:08.601+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO BlockManager: BlockManager stopped
[2025-02-21T13:08:08.606+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-02-21T13:08:08.607+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-02-21T13:08:08.619+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO SparkContext: Successfully stopped SparkContext
[2025-02-21T13:08:08.621+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Shutdown hook called
[2025-02-21T13:08:08.621+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-09e1431d-51fd-4e09-b558-508c70c339a9
[2025-02-21T13:08:08.633+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-f7596dd0-5975-492d-b598-a20f8eea399d
[2025-02-21T13:08:08.637+0000] {subprocess.py:106} INFO - 25/02/21 13:08:08 INFO ShutdownHookManager: Deleting directory /tmp/spark-09e1431d-51fd-4e09-b558-508c70c339a9/pyspark-b517a3df-eaad-4479-9589-a6f0e2fb921c
[2025-02-21T13:08:08.672+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-21T13:08:08.683+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T13:08:08.687+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ing_mov_20_21, task_id=run_spark_script, run_id=manual__2025-02-21T12:00:42.315427+00:00, execution_date=20250221T120042, start_date=20250221T123813, end_date=20250221T130808
[2025-02-21T13:08:08.714+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T13:08:08.714+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task run_spark_script (Bash command failed. The command returned a non-zero exit code 1.; 843)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T13:08:08.727+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-21T13:08:08.742+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T13:08:08.744+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
