[2025-02-12T19:37:10.188+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T19:37:10.216+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-12T19:31:14.402377+00:00 [queued]>
[2025-02-12T19:37:10.229+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-12T19:31:14.402377+00:00 [queued]>
[2025-02-12T19:37:10.287+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-12T19:37:10.427+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_spark_script> on 2025-02-12 19:31:14.402377+00:00
[2025-02-12T19:37:10.434+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T19:37:10.437+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ing_mov_20_21', 'run_spark_script', 'manual__2025-02-12T19:31:14.402377+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/scriptteste.py', '--cfg-path', '/tmp/tmpavd_jw5u']
[2025-02-12T19:37:10.438+0000] {standard_task_runner.py:72} INFO - Started process 69 to run task
[2025-02-12T19:37:10.439+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask run_spark_script
[2025-02-12T19:37:10.534+0000] {task_command.py:467} INFO - Running <TaskInstance: ing_mov_20_21.run_spark_script manual__2025-02-12T19:31:14.402377+00:00 [running]> on host b9a583b11a65
[2025-02-12T19:37:10.703+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ing_mov_20_21' AIRFLOW_CTX_TASK_ID='run_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T19:31:14.402377+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T19:31:14.402377+00:00'
[2025-02-12T19:37:10.709+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-12T19:37:10.764+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-12T19:37:10.766+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit opt/bitnami/spark/scripts/ing_mov_20_21.py']
[2025-02-12T19:37:10.780+0000] {subprocess.py:99} INFO - Output:
[2025-02-12T19:37:13.654+0000] {subprocess.py:106} INFO - python3: can't open file '/tmp/***tmpaumk90e2/opt/bitnami/spark/scripts/ing_mov_20_21.py': [Errno 2] No such file or directory
[2025-02-12T19:37:13.672+0000] {subprocess.py:106} INFO - 25/02/12 19:37:13 INFO ShutdownHookManager: Shutdown hook called
[2025-02-12T19:37:13.677+0000] {subprocess.py:106} INFO - 25/02/12 19:37:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-6701cc57-5494-4e47-a5e6-b3d12570fc11
[2025-02-12T19:37:13.710+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-02-12T19:37:13.725+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-12T19:37:13.731+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ing_mov_20_21, task_id=run_spark_script, run_id=manual__2025-02-12T19:31:14.402377+00:00, execution_date=20250212T193114, start_date=20250212T193710, end_date=20250212T193713
[2025-02-12T19:37:13.771+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-12T19:37:13.772+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 43 for task run_spark_script (Bash command failed. The command returned a non-zero exit code 2.; 69)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-02-12T19:37:13.795+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-12T19:37:13.816+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T19:37:13.820+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
